name: Individ_1


on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Build project
        run: dotnet build Проба_Фрингерпринтер/Проба_Фрингерпринтер.csproj --configuration ${{ matrix.configuration }}
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ matrix.configuration }}
          path: |
            Проба_Фрингерпринтер/bin/${{ matrix.configuration }}//*
            Проба_Фрингерпринтер/obj/${{ matrix.configuration }}//*
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Run tests
        run: dotnet test Tests/Tests.csproj --configuration ${{ matrix.configuration }}

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download Debug build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files-Debug
          path: dist/debug/
          
      - name: Download Release build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files-Release
          path: dist/release/
          
      - name: List downloaded files
        run: ls -la dist/
